config/routes.rb
Rails.application.routes.draw do
  resources :profiles

  devise_for :users
  get '/about' => 'site#about'
  get '/contact' => 'site#contact'
  get '/thankyou' => 'site#thankyou' 
  
  get '/admin' => 'user#admin_login'
  get '/logout' => 'user#logout'
  
  get '/cart' => 'cart#index'
  get '/cart/:id' => 'cart#add'
  
  get '/myprofile' => 'profiles#myprofile' 
  get '/Admin' => 'user#admin_login'
  get '/logout' => 'user#logout' 
  
  resources :items

  root 'site#about'

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # RESTful
  load_and_authorize_resource
  
  before_action :set_item, only: [:show, :edit, :update, :destroy] 
  before_action :set_item, only: [:show]

  # GET /items
  # GET /items.json
  
  def index
    if params[:category].blank?
      @items = Item.all
    else
      @items = Item.where(category: params[:category])
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :price, :image_url, :category)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%#= f.text_field :category %>
    <%= f.select :category, options_for_select( ['', 'Travel', 'Wildlife', 'Flowers', 'Landscapes'], @item.category) %>
    
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Products</h1>

<%= form_tag(items_path, method: :get) do %>
  <%= label_tag :category, 'Category: ' %>
  <%= select_tag :category, 
      options_for_select(
          ['', 'Travel', 'Wildlife', 'Flowers', 'Landscapes'],
          params[:category],
      ),
      onchange: 'this.form.submit();'
  %>
<% end %>

<table class="catalog">

<% @items.each do |item| %>
  <div class="itemstyle">
    
        <div class="image">
            <%= link_to (image_tag item.image_url, :style => "height:258px; width:258px"), item %>
        </div>
    
        <div class="title">
            <%= link_to item.title, item %>
        </div>
        <div class="description">
            <%=h item.description %>
        </div>
        <div class="price">
            <%= number_to_currency(item.price, :unit => "€") %>
        </div>
        <div class="links">
          <% if session[:login] == 1 %>
            <%= link_to 'Edit', edit_item_path(item) %> |
            <%= link_to 'Delete', item, :confirm => 'Are you sure?', :method => :delete %>
          <%else%>  
            <a href=/cart/<%=item.id %>">Add to Cart</a><br><br>
          <% end %>
        </div>
   </div>
<% end %>
</table>
<% if session[:login] == 1 %>
  <%= link_to 'New item', new_item_path %>
<% end %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @item.image_url %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category %>
</p>

<%# <%= link_to 'Edit', edit_item_path(@item) %> 
<%# | %>
<%= link_to 'Back', items_path %> 
|
<a href="/cart/<%= @item.id %>">Add to Cart</a> 